// apps/mobile/src/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import * as Sentry from '@sentry/react-native';
import { tokenStorage } from '@/utils/token-storage';

// ─── Translation dictionary ───────────────────────────────────────────────────
// Add every user-facing string here. Key = constant identifier.
// DE = German (default). EN = English.
export const TRANSLATIONS = {
  loading: { de: 'Lädt...', en: 'Loading...' },
  save: { de: 'Speichern', en: 'Save' },
  cancel: { de: 'Abbrechen', en: 'Cancel' },
  delete: { de: 'Löschen', en: 'Delete' },
  confirm: { de: 'Bestätigen', en: 'Confirm' },
  back: { de: 'Zurück', en: 'Back' },
  next: { de: 'Weiter', en: 'Next' },
  close: { de: 'Schließen', en: 'Close' },
  edit: { de: 'Bearbeiten', en: 'Edit' },
  done: { de: 'Fertig', en: 'Done' },
  send: { de: 'Senden', en: 'Send' },
  search: { de: 'Suchen', en: 'Search' },
  all: { de: 'Alle', en: 'All' },
  yes: { de: 'Ja', en: 'Yes' },
  no: { de: 'Nein', en: 'No' },
  logout: { de: 'Abmelden', en: 'Sign out' },
  errorUnknown: { de: 'Ein unbekannter Fehler ist aufgetreten.', en: 'An unknown error occurred.' },
  noResults: { de: 'Keine Ergebnisse', en: 'No results' },
  message: { de: 'Nachricht', en: 'Message' },
  call: { de: 'Anrufen', en: 'Call' },
  service: { de: 'Service', en: 'Service' },
  date: { de: 'Datum', en: 'Date' },
  time: { de: 'Zeit', en: 'Time' },
  networkErrorTryAgain: { de: 'Verbindungsfehler. Bitte erneut versuchen.', en: 'Connection error. Please try again.' },
  permissionMissingTitle: { de: 'Berechtigung erforderlich', en: 'Permission required' },
  photoPermissionBody: { de: 'Wir benötigen Zugriff auf deine Fotos.', en: 'We need access to your photos.' },
  avatarUploadFailed: { de: 'Das Bild konnte nicht hochgeladen werden.', en: 'The image could not be uploaded.' },
  pickImageError: { de: 'Fehler beim Auswählen des Bildes.', en: 'Error selecting the image.' },
  avatarPick: { de: 'Profilbild auswählen', en: 'Choose profile photo' },
  noBraidersNearbyTitle: { de: 'Keine Braider in deiner Nähe', en: 'No braiders nearby' },
  noBraidersNearbySubtitle: {
    de: 'Im Umkreis von {radius} km wurden aktuell keine Anbieter gefunden.',
    en: 'No providers were found within {radius} km at the moment.',
  },
  noBraidersNearbyChangeRadius: { de: 'Suchradius ändern', en: 'Change search radius' },
  mediaPickerTitle: { de: 'Anhang hinzufügen', en: 'Add attachment' },
  mediaPickerImageLabel: { de: 'Foto senden', en: 'Send photo' },
  mediaPickerImageSub: { de: 'Zeige deinen gewünschten Stil', en: 'Show your desired style' },
  mediaPickerDocumentLabel: { de: 'Dokument senden', en: 'Send document' },
  mediaPickerDocumentSub: { de: 'PDF-Dateien', en: 'PDF files' },
  calendarPreviousMonth: { de: 'Vorheriger Monat', en: 'Previous month' },
  calendarNextMonth: { de: 'Nächster Monat', en: 'Next month' },
  calendarAddBlockedTime: { de: 'Zeitblock hinzufügen', en: 'Add blocked time' },
  calendarDeleteBlockedTime: { de: 'Zeitblock löschen', en: 'Delete blocked time' },
  shareProfileAction: { de: 'Profil teilen', en: 'Share profile' },
  favouritesAddAction: { de: 'Zu Favoriten hinzufügen', en: 'Add to favourites' },
  favouritesRemoveAction: { de: 'Aus Favoriten entfernen', en: 'Remove from favourites' },
  chatCallContact: { de: 'Kontakt anrufen', en: 'Call contact' },
  chatSendMessage: { de: 'Nachricht senden', en: 'Send message' },
  legalOpenInBrowser: { de: '{title} im Browser öffnen', en: 'Open {title} in browser' },
  portfolioDeleteTitle: { de: 'Foto löschen', en: 'Delete photo' },
  portfolioDeleteBody: {
    de: 'Bist du sicher, dass du dieses Foto aus deinem Portfolio löschen möchtest?',
    en: 'Are you sure you want to delete this photo from your portfolio?',
  },
  portfolioUploadTitle: { de: 'Foto hochladen', en: 'Upload photo' },
  portfolioUploadChange: { de: 'Ändern', en: 'Change' },
  portfolioUploadPick: { de: 'Foto auswählen', en: 'Choose a photo' },
  portfolioUploadCaptionOptional: { de: 'Caption (optional)', en: 'Caption (optional)' },
  portfolioUploadCaptionPlaceholder: { de: 'Beschreibe diesen Style...', en: 'Describe this style...' },
  portfolioUploadStyleTags: { de: 'Style-Tags', en: 'Style tags' },
  portfolioUploadCustomTagPlaceholder: { de: 'Eigener Tag...', en: 'Custom tag...' },
  portfolioUploadAddTag: { de: 'Tag hinzufügen', en: 'Add tag' },
  portfolioUploadButton: { de: 'Hochladen', en: 'Upload' },
  portfolioEmptySub: { de: 'Zeige deine Arbeit und gewinne mehr Kunden', en: 'Show your work and gain more clients' },
  portfolioTagKnotless: { de: 'Knotless', en: 'Knotless' },
  portfolioTagBoxBraids: { de: 'Box Braids', en: 'Box Braids' },
  portfolioTagCornrows: { de: 'Cornrows', en: 'Cornrows' },
  portfolioTagTwists: { de: 'Twists', en: 'Twists' },
  portfolioTagLocs: { de: 'Locs', en: 'Locs' },
  portfolioTagFades: { de: 'Fades', en: 'Fades' },
  switchToClientTitle: { de: 'Zu anderem Kunden-Konto wechseln', en: 'Switch to a client account' },
  switchToClientBody: {
    de: 'Du wirst abgemeldet und kannst dich danach mit einem separaten Kunden-Konto anmelden.',
    en: 'You will be signed out and can then sign in with a separate client account.',
  },
  myProfile: { de: 'Mein Profil', en: 'My profile' },
  notSpecified: { de: 'Nicht angegeben', en: 'Not specified' },
  providerVerified: { de: '✓ Verifiziert', en: '✓ Verified' },
  providerUnderReview: { de: '⏳ Prüfung läuft', en: '⏳ Under review' },
  providerProfilePreview: { de: 'Profilvorschau', en: 'Profile preview' },
  providerServicesPrices: { de: 'Services & Preise', en: 'Services & prices' },
  providerPortfolio: { de: 'Portfolio', en: 'Portfolio' },
  providerSwitchToClient: { de: '👤 Mit anderem Kunden-Konto anmelden', en: '👤 Sign in with a different client account' },
  saving: { de: 'Speichert...', en: 'Saving...' },
  fieldRequired: { de: 'Pflichtfeld', en: 'Required' },
  selectPlease: { de: 'Bitte wählen', en: 'Please select' },
  invalidValue: { de: 'Ungültig', en: 'Invalid' },
  enterValidPrice: { de: 'Gültigen Preis eingeben', en: 'Enter a valid price' },
  active: { de: 'Aktiv', en: 'Active' },
  serviceActiveHelper: { de: 'Kunden können diesen Service buchen', en: 'Customers can book this service' },
  serviceCategory: { de: 'Kategorie', en: 'Category' },
  serviceName: { de: 'Service-Name', en: 'Service name' },
  serviceNamePlaceholder: { de: 'z.B. Knotless Braids', en: 'e.g. Knotless Braids' },
  serviceDescriptionOptional: { de: 'Beschreibung (Optional)', en: 'Description (Optional)' },
  serviceDescriptionPlaceholder: { de: 'Infos für den Kunden', en: 'Info for the customer' },
  serviceDurationMinutes: { de: 'Dauer (Minuten)', en: 'Duration (minutes)' },
  hoursShort: { de: 'Std.', en: 'hr' },
  minutesShort: { de: 'Min.', en: 'min' },
  servicePriceType: { de: 'Preis-Typ', en: 'Price type' },
  servicePriceTypeFixed: { de: 'Festpreis', en: 'Fixed price' },
  servicePriceTypeFrom: { de: 'Ab-Preis', en: 'From' },
  servicePriceEuro: { de: 'Preis (€)', en: 'Price (€)' },
  passwordsDontMatch: { de: 'Passwörter stimmen nicht überein.', en: 'Passwords do not match.' },
  acceptTermsRequired: { de: 'Bitte akzeptiere die AGB und die Datenschutzerklärung.', en: 'Please accept the terms and privacy policy.' },
  registerClientTitle: { de: 'Kundenkonto erstellen', en: 'Create client account' },
  registerCreateAccount: { de: 'Konto erstellen', en: 'Create account' },
  registerAlreadyHaveAccount: { de: 'Bereits registriert? Anmelden', en: 'Already registered? Sign in' },
  backToLogin: { de: 'Zurück zum Login', en: 'Back to sign in' },
  contactSupport: { de: 'Support kontaktieren', en: 'Contact support' },
  providerPendingConnectionFailed: { de: 'Verbindung zum Server fehlgeschlagen. Bitte starte die App neu.', en: 'Connection to the server failed. Please restart the app.' },
  providerPendingProcessingTime: { de: 'Bearbeitungszeit', en: 'Processing time' },
  providerPendingProcessingValue: { de: '1-3 Werktage', en: '1–3 business days' },
  providerPendingEmailNotice: { de: 'Du erhältst eine E-Mail sobald dein Account freigeschaltet wurde.', en: 'You will receive an email once your account has been approved.' },
  providerPendingSpamNotice: { de: 'Prüfe auch deinen Spam-Ordner.', en: 'Also check your spam folder.' },
  providerPendingTitle: { de: 'Registrierung wird geprüft', en: 'Registration under review' },
  providerPendingBody: {
    de: 'Deine Registrierung wird gerade von unserem Team überprüft.\nDies dauert in der Regel {time}.',
    en: 'Your registration is currently being reviewed by our team.\nThis usually takes {time}.',
  },
  providerPendingStep1Title: { de: 'Registrierung eingereicht', en: 'Registration submitted' },
  providerPendingStep1Sub: { de: 'Deine Daten wurden erfolgreich übermittelt', en: 'Your details were submitted successfully' },
  providerPendingStep2Title: { de: 'Überprüfung läuft', en: 'Review in progress' },
  providerPendingStep2Sub: { de: 'Unser Team prüft deine Angaben', en: 'Our team is reviewing your details' },
  providerPendingStep3Title: { de: 'Freischaltung', en: 'Activation' },
  providerPendingStep3Sub: { de: 'Du erhältst eine Bestätigungs-E-Mail', en: 'You will receive a confirmation email' },
  languageGerman: { de: 'Deutsch', en: 'German' },
  languageEnglish: { de: 'Englisch', en: 'English' },
  languageFrench: { de: 'Französisch', en: 'French' },
  languageArabic: { de: 'Arabisch', en: 'Arabic' },
  languageTurkish: { de: 'Türkisch', en: 'Turkish' },
  languageHausa: { de: 'Hausa', en: 'Hausa' },
  languageYoruba: { de: 'Yoruba', en: 'Yoruba' },
  languageIgbo: { de: 'Igbo', en: 'Igbo' },
  verifyEmailTitle: { de: 'E-Mail bestätigen', en: 'Verify email' },
  verifyEmailBody: { de: 'Wir haben dir einen Code an {email} gesendet.', en: 'We sent a code to {email}.' },
  verifyEmailResend: { de: 'Code erneut senden', en: 'Resend code' },
  verifyEmailInvalidCode: { de: 'Ungültiger Code. Bitte versuche es erneut.', en: 'Invalid code. Please try again.' },
  verifyEmailExpiredCode: { de: 'Code abgelaufen. Bitte fordere einen neuen an.', en: 'Code expired. Please request a new one.' },
  verifyEmailTooManyRequests: { de: 'Du hast zu oft einen Code angefordert. Bitte versuche es später erneut.', en: 'You requested a code too many times. Please try again later.' },
  yourEmailAddress: { de: 'deine E-Mail-Adresse', en: 'your email address' },
  enterYourEmail: { de: 'Bitte gib deine E-Mail-Adresse ein.', en: 'Please enter your email address.' },
  otpEnter6Digits: { de: 'Bitte gib den 6-stelligen Code ein.', en: 'Please enter the 6-digit code.' },
  resetVerificationFailed: { de: 'Code-Verifizierung fehlgeschlagen. Bitte starte den Vorgang neu.', en: 'Code verification failed. Please restart the process.' },
  passwordResetTitle: { de: 'Passwort vergessen?', en: 'Forgot password?' },
  passwordResetBody: { de: 'Gib deine E-Mail-Adresse ein, um einen Code zu erhalten.', en: 'Enter your email address to receive a code.' },
  passwordResetSendCode: { de: 'Code senden', en: 'Send code' },
  passwordResetEnterCodeTitle: { de: 'Code eingeben', en: 'Enter code' },
  passwordResetEnterCodeBody: { de: 'Bitte gib den 6-stelligen Code ein, der an deine E-Mail gesendet wurde.', en: 'Enter the 6-digit code that was sent to your email.' },
  passwordResetNewPasswordTitle: { de: 'Neues Passwort', en: 'New password' },
  passwordResetNewPasswordBody: { de: 'Bitte gib ein sicheres neues Passwort ein.', en: 'Please enter a secure new password.' },
  passwordResetNewPasswordLabel: { de: 'Neues Passwort', en: 'New password' },
  passwordResetSavePassword: { de: 'Passwort speichern', en: 'Save password' },
  providerTypeTitle: { de: 'Was beschreibt dich am besten?', en: 'What describes you best?' },
  providerTypeSubtitle: { de: 'Wähle deine Kontoart aus', en: 'Choose your account type' },
  providerTypeFreelancerTitle: { de: 'Einzelperson / Freelancer', en: 'Individual / Freelancer' },
  providerTypeFreelancerSub: { de: 'Ich arbeite selbstständig', en: 'I work independently' },
  providerTypeSalonTitle: { de: 'Salon / Barbershop', en: 'Salon / Barbershop' },
  providerTypeSalonSub: { de: 'Ich habe ein Geschäft', en: 'I have a shop' },
  providerTypeMobileTitle: { de: 'Mobiler Service', en: 'Mobile service' },
  providerTypeMobileSub: { de: 'Ich komme zu meinen Kunden', en: 'I travel to my customers' },
  providerTypeBarberTitle: { de: 'Barber', en: 'Barber' },
  providerTypeBarberSub: { de: 'Haar- und Bartpflege', en: 'Hair and beard care' },
  providerRegisterProgress: { de: 'Schritt {step} / {total}', en: 'Step {step} / {total}' },
  providerRegisterStep1Title: { de: 'Persönliche Daten', en: 'Personal details' },
  providerRegisterStep1Subtitle: { de: 'Bitte gib deine Daten ein', en: 'Please enter your details' },
  providerRegisterPhoneLabel: { de: 'Telefon (+49...)', en: 'Phone (+49...)' },
  providerRegisterPasswordPlaceholder: { de: 'Mindestens 8 Zeichen', en: 'At least 8 characters' },
  providerRegisterPasswordConfirmPlaceholder: { de: 'Passwort wiederholen', en: 'Repeat password' },
  providerRegisterTermsPrefix: { de: 'Ich akzeptiere die', en: 'I accept the' },
  providerRegisterTermsProviders: { de: 'AGB für Anbieter', en: 'provider terms' },
  providerRegisterTermsAnd: { de: 'und', en: 'and' },
  providerRegisterTermsPrivacy: { de: 'Datenschutzerklärung', en: 'privacy policy' },
  providerRegisterFirstNameRequired: { de: 'Vorname ist erforderlich', en: 'First name is required' },
  providerRegisterLastNameRequired: { de: 'Nachname ist erforderlich', en: 'Last name is required' },
  providerRegisterEmailRequired: { de: 'E-Mail ist erforderlich', en: 'Email is required' },
  providerRegisterEmailInvalid: { de: 'Bitte gib eine gültige E-Mail-Adresse ein', en: 'Please enter a valid email address' },
  providerRegisterPhoneRequired: { de: 'Telefonnummer ist erforderlich', en: 'Phone number is required' },
  providerRegisterPhoneInvalid: { de: 'Bitte gib eine gültige deutsche Telefonnummer ein. (+49...)', en: 'Please enter a valid German phone number. (+49...)' },
  providerRegisterPasswordRequired: { de: 'Passwort ist erforderlich', en: 'Password is required' },
  providerRegisterPasswordTooShort: { de: 'Passwort muss mindestens 8 Zeichen lang sein', en: 'Password must be at least 8 characters' },
  providerRegisterAcceptTermsRequired: { de: 'Bitte akzeptiere die AGB.', en: 'Please accept the terms.' },
  providerRegisterStep2Title: { de: 'Business Profil', en: 'Business profile' },
  providerRegisterStep2Subtitle: { de: 'Gib die Details deines Geschäfts ein', en: 'Enter your business details' },
  providerRegisterBusinessNameRequired: { de: 'Business-Name ist erforderlich', en: 'Business name is required' },
  providerRegisterStreetRequired: { de: 'Straße ist erforderlich', en: 'Street is required' },
  providerRegisterHouseNumberRequired: { de: 'Nr. ist erforderlich', en: 'House number is required' },
  providerRegisterPostalCodeRequired: { de: 'PLZ ist erforderlich', en: 'Postal code is required' },
  providerRegisterCityRequired: { de: 'Stadt ist erforderlich', en: 'City is required' },
  providerRegisterRadiusLabel: { de: 'Radius: {km} km', en: 'Radius: {km} km' },
  providerRegisterBusinessNamePlaceholder: { de: 'Mein Salon', en: 'My salon' },
  providerRegisterStreetPlaceholder: { de: 'Hauptstraße', en: 'Main street' },

  providerRegisterStep3SpecialisationsTitle: { de: 'Spezialisierungen', en: 'Specialisations' },
  providerRegisterStep3SpecialisationsSubtitle: { de: 'Welche Services bietest du an?', en: 'Which services do you offer?' },
  providerRegisterStep3ServicesLoadError: { de: 'Dienste konnten nicht geladen werden.', en: 'Services could not be loaded.' },
  providerRegisterStep3ExperienceTitle: { de: 'Erfahrung', en: 'Experience' },
  providerRegisterStep3ExperienceYears: { de: '{years} Jahre Erfahrung', en: '{years} years of experience' },
  providerRegisterStep3LanguagesTitle: { de: 'Sprachen', en: 'Languages' },
  providerRegisterStep3LanguagesRequired: { de: 'Bitte wähle mindestens eine Sprache aus.', en: 'Please select at least one language.' },
  providerRegisterStep3CancellationTitle: { de: 'Stornierungsrichtlinie', en: 'Cancellation policy' },
  providerRegisterStep3AboutTitle: { de: 'Über mich (optional)', en: 'About me (optional)' },
  providerRegisterStep3BioPlaceholder: { de: 'Erzähle Kunden von dir und deiner Arbeit...', en: 'Tell customers about you and your work...' },

  providerRegisterStep4ProfilePhotoTitle: { de: 'Profilbild', en: 'Profile photo' },
  providerRegisterStep4AddPhoto: { de: 'Foto hinzufügen', en: 'Add photo' },
  providerRegisterStep4IdTitle: { de: 'Ausweis / Reisepass', en: 'ID / Passport' },
  providerRegisterStep4IdUploaded: { de: 'Ausweis hochgeladen', en: 'ID uploaded' },
  providerRegisterStep4Change: { de: 'Ändern', en: 'Change' },
  providerRegisterStep4UploadId: { de: 'Ausweis hochladen', en: 'Upload ID' },
  providerRegisterStep4IdSubtitle: { de: 'Personalausweis oder Reisepass', en: 'National ID or passport' },
  providerRegisterStep4PortfolioTitle: { de: 'Portfolio (mind. 1 Foto)', en: 'Portfolio (min. 1 photo)' },

  providerRegisterSummaryTitle: { de: 'Zusammenfassung', en: 'Summary' },
  providerRegisterSummarySubtitle: { de: 'Bitte prüfe deine Angaben vor dem Absenden.', en: 'Please review your details before submitting.' },
  providerRegisterSummaryBusinessTitle: { de: 'Geschäftsinformationen', en: 'Business information' },
  providerRegisterSummaryServicesTitle: { de: 'Services & Erfahrung', en: 'Services & experience' },
  providerRegisterSummaryServicesSelected: { de: '{count} Services gewählt', en: '{count} services selected' },
  providerRegisterSummaryPortfolioTitle: { de: 'Portfolio', en: 'Portfolio' },
  providerRegisterSummaryProfilePhotoOk: { de: '✓ Profilbild', en: '✓ Profile photo' },
  providerRegisterSummaryProfilePhotoMissing: { de: '✗ Profilbild fehlt', en: '✗ Missing profile photo' },
  providerRegisterSummaryPortfolioPhotos: { de: '{count} Portfolio-Fotos', en: '{count} portfolio photos' },
  providerRegisterSummaryIdOk: { de: '✓ Ausweis', en: '✓ ID' },
  providerRegisterSummaryIdMissing: { de: '✗ Ausweis fehlt', en: '✗ Missing ID' },

  providerRegisterNextStepsTitle: { de: 'WAS PASSIERT JETZT?', en: "WHAT'S NEXT?" },
  providerRegisterNextStep1Title: { de: 'Prüfung deiner Angaben', en: 'Reviewing your details' },
  providerRegisterNextStep2Title: { de: 'Verifizierung deines Ausweises', en: 'Verifying your ID' },
  providerRegisterNextStep3Title: { de: 'Freischaltung deines Profils', en: 'Activating your profile' },
  providerRegisterNextStep4Title: { de: 'Bestätigungs-E-Mail', en: 'Confirmation email' },
  providerRegisterNextStepTime24h: { de: '~24 Stunden', en: '~24 hours' },
  providerRegisterNextStepTime1h: { de: '~1 Stunde', en: '~1 hour' },
  providerRegisterNextStepTimeImmediate: { de: 'Sofort', en: 'Immediately' },

  providerRegisterSubmit: { de: 'Registrierung absenden', en: 'Submit registration' },
  providerRegisterSubmittingAccount: { de: 'Konto wird erstellt...', en: 'Creating account...' },
  providerRegisterEmailTaken: { de: 'Diese E-Mail-Adresse ist bereits registriert.', en: 'This email address is already registered.' },
  providerRegisterAccountCreateFailed: { de: 'Konto konnte nicht erstellt werden.', en: 'Account could not be created.' },
  providerRegisterUploadingProfilePhoto: { de: 'Profilbild wird hochgeladen...', en: 'Uploading profile photo...' },
  providerRegisterCreatingProfile: { de: 'Profil wird erstellt...', en: 'Creating profile...' },
  providerRegisterProfileCreateFailed: {
    de: 'Profil konnte nicht erstellt werden. Bitte überprüfe deine Angaben und versuche es erneut.',
    en: 'Profile could not be created. Please check your details and try again.',
  },
  providerRegisterUploadingId: { de: 'Ausweis wird hochgeladen...', en: 'Uploading ID...' },
  providerRegisterUploadingPortfolio: { de: 'Portfolio wird hochgeladen...', en: 'Uploading portfolio...' },

  error: { de: 'Fehler', en: 'Error' },
  errorOpenLink: { de: 'Konnte den Link nicht öffnen.', en: 'Could not open the link.' },
  enterPassword: { de: 'Bitte Passwort eingeben', en: 'Please enter your password.' },
  notAvailable: { de: 'N/A', en: 'N/A' },
  clientNameDefault: { de: 'Kunde', en: 'Client' },
  providerGeneric: { de: 'Anbieter', en: 'Provider' },
  countryDefault: { de: 'Deutschland', en: 'Germany' },
  cityNotFound: { de: 'Stadt nicht gefunden.', en: 'City not found.' },
  locationUpdateFailed: { de: 'Standort konnte nicht aktualisiert werden.', en: 'Could not update location.' },
  locationPermissionNeeded: {
    de: 'Standortzugriff wird benötigt, um Braider nach Entfernung zu sortieren.',
    en: 'Location access is required to sort braiders by distance.',
  },
  phoneMissingTitle: { de: 'Keine Telefonnummer', en: 'No phone number' },
  phoneMissingBody: { de: 'Der Kunde hat keine Telefonnummer hinterlegt.', en: 'The customer has no phone number on file.' },
  providerAppointmentDetailsTitle: { de: 'Termindetails', en: 'Appointment Details' },
  providerAppointmentNotFound: { de: 'Termin nicht gefunden', en: 'Appointment not found' },
  providerBookingNumberLabel: { de: 'Buchungsnummer', en: 'Booking number' },
  providerUnknownCity: { de: 'Stadt unbekannt', en: 'City unknown' },
  providerPayout: { de: 'Deine Auszahlung', en: 'Your payout' },
  providerPaymentOnCompletion: { de: 'Zahlung bei Abschluss', en: 'Payment on completion' },
  providerBookingAccept: { de: 'Buchung annehmen', en: 'Accept booking' },
  providerStartAppointment: { de: 'Termin starten', en: 'Start appointment' },
  providerBookingAcceptError: { de: 'Buchung konnte nicht bestätigt werden.', en: 'Booking could not be accepted.' },
  providerBookingDeclineError: { de: 'Buchung konnte nicht abgelehnt werden.', en: 'Booking could not be declined.' },
  calendarDeleteBlockTitle: { de: 'Zeitblock löschen', en: 'Delete block' },
  calendarDeleteBlockBody: {
    de: 'Möchtest du den Block "{reason}" wirklich löschen?',
    en: 'Do you really want to delete the block "{reason}"?',
  },
  calendarDeleteBlockFallbackReason: { de: 'Zeitblock', en: 'Block' },
  calendarDeleteBlockError: { de: 'Der Zeitblock konnte nicht gelöscht werden.', en: 'The block could not be deleted.' },

  login: { de: 'Anmelden', en: 'Sign in' },
  register: { de: 'Registrieren', en: 'Register' },
  email: { de: 'E-Mail', en: 'Email' },
  phone: { de: 'Telefon', en: 'Phone' },
  password: { de: 'Passwort', en: 'Password' },
  passwordConfirm: { de: 'Passwort bestätigen', en: 'Confirm password' },
  showPassword: { de: 'Passwort anzeigen', en: 'Show password' },
  hidePassword: { de: 'Passwort verbergen', en: 'Hide password' },
  firstName: { de: 'Vorname', en: 'First name' },
  lastName: { de: 'Nachname', en: 'Last name' },
  forgotPassword: { de: 'Passwort vergessen?', en: 'Forgot password?' },
  welcomeBack: { de: 'Willkommen zurück!', en: 'Welcome back!' },
  noAccount: { de: 'Noch kein Konto? Jetzt registrieren', en: "Don't have an account? Register" },
  acceptTerms: { de: 'Ich akzeptiere die AGB und Datenschutzerklärung', en: 'I accept the terms and privacy policy' },
  splashTagline: { de: 'Verbinde dich mit deinem perfekten Style', en: 'Connect with your perfect style' },
  roleClient: { de: 'Kunde', en: 'Client' },
  roleProvider: { de: 'Anbieter', en: 'Provider' },
  loginIdentifier: { de: 'E-Mail / Telefon', en: 'Email / phone' },
  loginNoAccountClient: { de: 'Noch kein Konto? Als Kunde registrieren', en: 'No account yet? Register as a client' },
  loginNoAccountProvider: { de: 'Noch kein Konto? Als Anbieter registrieren', en: 'No account yet? Register as a provider' },
  accountTypeTitle: { de: 'Willkommen bei HairConnekt', en: 'Welcome to HairConnekt' },
  accountTypeClientTitle: { de: 'Ich suche einen Friseur', en: 'I’m looking for a stylist' },
  accountTypeClientSubtitle: { de: 'Finde Braider, Salons & Stylisten in deiner Nähe', en: 'Find braiders, salons & stylists near you' },
  accountTypeProviderTitle: { de: 'Ich biete Friseur-Services an', en: 'I offer hair services' },
  accountTypeProviderSubtitle: { de: 'Zeige deine Arbeit und gewinne neue Kunden', en: 'Show your work and gain new customers' },

  tabHome: { de: 'Startseite', en: 'Home' },
  tabSearch: { de: 'Suchen', en: 'Search' },
  tabAppointments: { de: 'Termine', en: 'Appointments' },
  tabMessages: { de: 'Nachrichten', en: 'Messages' },
  tabProfile: { de: 'Profil', en: 'Profile' },
  tabCalendar: { de: 'Termine', en: 'Calendar' },

  homeGreeting: { de: 'Hallo', en: 'Hello' },
  homeNearby: { de: 'Braiders in deiner Nähe', en: 'Braiders near you' },
  homePopular: { de: 'Beliebte Styles', en: 'Popular styles' },
  homeViewAll: { de: 'Alle anzeigen', en: 'View all' },
  homeSearchPlaceholder: { de: 'Suche nach Styles, Braiders, Salons...', en: 'Search styles, braiders, salons...' },
  homeNoBraiders: { de: 'Keine Braider verfügbar', en: 'No braiders available' },
  homeLocationLabel: { de: 'Standort ändern', en: 'Change location' },
  homeLocationModal: { de: 'Stadt eingeben', en: 'Enter city' },
  homeLocationBody: {
    de: 'Gib eine Stadt ein, um dort Anbieter zu sehen und zu buchen.',
    en: 'Enter a city to browse providers and book there.',
  },
  homeLocationPlaceholder: { de: 'z. B. Berlin, Hamburg...', en: 'e.g. Berlin, Hamburg...' },
  homeLocationApply: { de: 'Anwenden', en: 'Apply' },
  homeLocationGps: { de: 'GPS-Standort verwenden', en: 'Use GPS location' },

  searchResults: { de: 'Braider gefunden', en: 'braiders found' },
  searchEmpty: { de: 'Keine Ergebnisse für deine Suche', en: 'No results for your search' },
  searchAvailableToday: { de: 'Verfügbar heute', en: 'Available today' },
  searchClear: { de: 'Suche löschen', en: 'Clear search' },
  searchSort: { de: 'Sortieren', en: 'Sort' },
  searchSortRecommended: { de: 'Empfohlen', en: 'Recommended' },
  searchSortDistance: { de: 'Entfernung', en: 'Distance' },
  searchSortRating: { de: 'Bewertung', en: 'Rating' },

  cardFrom: { de: 'ab', en: 'from' },
  cardAvailableToday: { de: 'Heute verfügbar', en: 'Available today' },
  cardReviews: { de: 'Bewertungen', en: 'reviews' },
  cardPriceOnRequest: { de: 'Preis auf Anfrage', en: 'Price on request' },

  profileTabOverview: { de: 'Überblick', en: 'Overview' },
  profileTabServices: { de: 'Services', en: 'Services' },
  profileTabGallery: { de: 'Galerie', en: 'Gallery' },
  profileTabReviews: { de: 'Bewertungen', en: 'Reviews' },
  profileBio: { de: 'Über mich', en: 'About me' },
  profileSpecialisations: { de: 'Spezialisierungen', en: 'Specialisations' },
  profileInfo: { de: 'Informationen', en: 'Information' },
  profileCancellation: { de: 'Stornierungsbedingungen', en: 'Cancellation policy' },
  profileBookNow: { de: 'Termin buchen', en: 'Book appointment' },
  profileMessage: { de: 'Nachricht', en: 'Message' },
  profilePrices: { de: 'Preise', en: 'Prices' },
  profileVerified: { de: 'Verifiziert', en: 'Verified' },
  profileNoPhotos: { de: 'Noch keine Fotos', en: 'No photos yet' },
  profileNoServices: { de: 'Noch keine Services', en: 'No services yet' },
  profileNoReviews: { de: 'Noch keine Bewertungen', en: 'No reviews yet' },
  profileResponseTime: { de: 'Antwortet in', en: 'Responds within' },
  profileSelectService: { de: 'Auswählen', en: 'Select' },
  profileNoSpecialisations: { de: 'Keine Spezialisierungen angegeben.', en: 'No specialisations provided.' },

  previewBanner: { de: '👁 Vorschau-Modus', en: '👁 Preview mode' },
  previewEdit: { de: 'Bearbeiten', en: 'Edit' },
  previewBookDisabled: { de: 'Termin buchen', en: 'Book appointment' },
  previewNote: { de: '(Vorschau — Kunden buchen hier)', en: '(Preview — customers book here)' },

  bookingStep: { de: 'Schritt', en: 'Step' },
  bookingOf: { de: 'von', en: 'of' },
  bookingSelectService: { de: 'Services auswählen', en: 'Select services' },
  bookingSelected: { de: 'ausgewählt', en: 'selected' },
  bookingTotal: { de: 'Gesamt', en: 'Total' },
  bookingServices: { de: 'Services', en: 'Services' },
  bookingSelectDate: { de: 'Datum & Zeit', en: 'Date & Time' },
  bookingAvailableTimes: { de: 'Verfügbare Zeiten', en: 'Available times' },
  bookingNoSlots: { de: 'Keine freien Termine an diesem Tag.', en: 'No available slots on this day.' },
  bookingChooseDate: { de: 'Wähle ein Datum', en: 'Choose a date' },
  bookingDetails: { de: 'Buchungsdetails', en: 'Booking details' },
  bookingMobileService: { de: 'Mobiler Service gewünscht', en: 'Mobile service requested' },
  bookingMobileSub: { de: 'Der Braider kommt zu dir nach Hause', en: 'The braider comes to you' },
  bookingNotes: { de: 'Notizen für den Braider', en: 'Notes for the braider' },
  bookingNotesPlaceholder: { de: 'Besondere Wünsche, Haartyp, Allergien...', en: 'Special requests, hair type, allergies...' },
  bookingPayment: { de: 'Zahlung', en: 'Payment' },
  bookingPaymentMethod: { de: 'Vor Ort bar zahlen', en: 'Pay cash on site' },
  bookingPaymentSub: { de: 'Bezahle direkt beim Termin', en: 'Pay directly at the appointment' },
  bookingBookNow: { de: 'Jetzt buchen', en: 'Book now' },
  bookingConfirmed: { de: 'Termin bestätigt! 🎉', en: 'Appointment confirmed! 🎉' },
  bookingNumber: { de: 'Buchungsnummer', en: 'Booking number' },
  bookingWhatsNext: { de: 'WAS KOMMT ALS NÄCHSTES?', en: "WHAT'S NEXT?" },
  bookingConfirmEmail: { de: 'Bestätigung per E-Mail', en: 'Confirmation by email' },
  bookingConfirmSoon: { de: 'Sofort', en: 'Immediately' },
  bookingProviderConfirms: { de: 'Anbieter bestätigt deinen Termin', en: 'Provider confirms your appointment' },
  bookingReminder: { de: 'Erinnerung 24h vor dem Termin', en: 'Reminder 24h before appointment' },
  bookingAutomatic: { de: 'Automatisch', en: 'Automatic' },
  bookingSendMessage: { de: 'Nachricht senden', en: 'Send message' },
  bookingServicePrice: { de: 'Service-Preis', en: 'Service price' },
  bookingPlatformFee: { de: 'Plattform-Gebühr', en: 'Platform fee' },
  bookingYourPayout: { de: 'Deine Auszahlung', en: 'Your payout' },
  bookingPaymentOnSite: { de: 'Zahlung bei Abschluss', en: 'Payment on completion' },
  bookingAtLeastOne: { de: 'Mind. 1 Service erforderlich', en: 'At least 1 service required' },
  bookingNoServices: { de: 'Gegenwärtig werden keine Services angeboten.', en: 'No services are currently offered.' },
  bookingInvalidSlot: {
    de: 'Dieser Termin ist leider nicht möglich. Bitte wähle ein anderes Datum oder Uhrzeit.',
    en: 'This appointment is not possible. Please choose another date or time.',
  },
  bookingSlotTaken: {
    de: 'Dieser Zeitslot ist bereits vergeben. Bitte wähle eine andere Zeit.',
    en: 'This time slot is already taken. Please choose another time.',
  },

  appointmentsTitle: { de: 'Meine Termine', en: 'My appointments' },
  appointmentsUpcoming: { de: 'Anstehend', en: 'Upcoming' },
  appointmentsCompleted: { de: 'Abgeschlossen', en: 'Completed' },
  appointmentsCancelled: { de: 'Abgesagt', en: 'Cancelled' },
  appointmentsEmpty: { de: 'Keine anstehenden Termine', en: 'No upcoming appointments' },
  appointmentsRoute: { de: 'Route', en: 'Route' },
  appointmentsDetail: { de: 'Termindetails', en: 'Appointment details' },
  appointmentsDuration: { de: 'Dauer', en: 'Duration' },
  appointmentsDate: { de: 'Datum & Zeit', en: 'Date & Time' },
  appointmentsTotalPrice: { de: 'Gesamtpreis', en: 'Total price' },
  appointmentsCancelPolicy: { de: 'Stornierungsrichtlinie', en: 'Cancellation policy' },
  appointmentsReschedule: { de: 'Termin verschieben', en: 'Reschedule appointment' },
  appointmentsCancel: { de: 'Termin stornieren', en: 'Cancel appointment' },
  appointmentsWriteReview: { de: 'Bewertung schreiben', en: 'Write a review' },
  appointmentsCall: { de: 'Anrufen', en: 'Call' },
  appointmentsBooked: { de: 'Gebucht', en: 'Booked' },
  appointmentsStatusTimeline: { de: 'Status', en: 'Status' },
  appointmentsHours: { de: 'Std.', en: 'hr' },
  appointmentsMinutes: { de: 'Min.', en: 'min' },
  appointmentsNotFound: { de: 'Termin nicht gefunden', en: 'Appointment not found' },
  appointmentsRetry: { de: 'Erneut versuchen', en: 'Try again' },

  statusPending: { de: 'Ausstehend', en: 'Pending' },
  statusConfirmed: { de: 'Bestätigt', en: 'Confirmed' },
  statusInProgress: { de: 'In Bearbeitung', en: 'In progress' },
  statusCompleted: { de: 'Abgeschlossen', en: 'Completed' },
  statusCancelled: { de: 'Storniert', en: 'Cancelled' },

  cancelTitle: { de: 'Termin stornieren', en: 'Cancel appointment' },
  cancelConfirmTitle: { de: 'Termin wirklich stornieren?', en: 'Cancel this appointment?' },
  cancelConfirmBody: {
    de: 'Möchtest du diesen Termin wirklich stornieren? Diese Aktion kann nicht rückgängig gemacht werden.',
    en: 'Do you really want to cancel this appointment? This action cannot be undone.',
  },
  cancelPolicy: { de: 'Stornierungsrichtlinie', en: 'Cancellation policy' },
  cancelPolicyText: {
    de: 'Kostenlose Stornierung bis 24 Stunden vor Termin möglich. Bei kurzfristigerer Stornierung kann eine Gebühr von 50% anfallen.',
    en: 'Free cancellation up to 24 hours before the appointment. A 50% fee may apply for late cancellations.',
  },
  cancelPolicyUrgent: {
    de: 'Kurzfristige Stornierung (weniger als 24h). Eine Gebühr von 50% des Servicepreises kann anfallen.',
    en: 'Late cancellation (less than 24h). A fee of 50% of the service price may apply.',
  },
  cancelReason: { de: 'Grund für Stornierung', en: 'Reason for cancellation' },
  cancelReasonOther: { de: 'Andere Pläne', en: 'Other plans' },
  cancelReasonSick: { de: 'Gesundheitliche Gründe', en: 'Health reasons' },
  cancelReasonEmergency: { de: 'Notfall', en: 'Emergency' },
  cancelReasonProvider: { de: 'Möchte einen anderen Anbieter', en: 'Want a different provider' },
  cancelReasonMisc: { de: 'Sonstiges', en: 'Other' },
  cancelConfirmBtn: { de: 'Termin stornieren', en: 'Cancel appointment' },
  cancelNotes: { de: 'Zusätzliche Anmerkungen (optional)', en: 'Additional notes (optional)' },
  cancelNotesPlaceholder: { de: 'Möchtest du noch etwas hinzufügen?', en: 'Would you like to add anything?' },
  cancelProviderNotified: { de: 'Der Anbieter wird über die Stornierung informiert', en: 'The provider will be notified of the cancellation' },
  cancelNotAllowed: { de: 'Dieser Termin kann nicht mehr storniert werden.', en: 'This appointment can no longer be cancelled.' },

  rescheduleTitle: { de: 'Termin verschieben', en: 'Reschedule appointment' },
  rescheduleCurrentBooking: { de: 'Dein aktueller Termin', en: 'Your current appointment' },
  rescheduleNewDate: { de: 'Neues Datum', en: 'New date' },
  rescheduleReason: { de: 'Grund für Verschiebung (optional)', en: 'Reason for rescheduling (optional)' },
  rescheduleReasonPlaceholder: { de: 'Bitte gib einen Grund an...', en: 'Please provide a reason...' },
  rescheduleConfirm: { de: 'Termin verschieben', en: 'Reschedule' },

  reviewsTitle: { de: 'Bewertungen', en: 'Reviews' },
  reviewWrite: { de: 'Bewertung schreiben', en: 'Write review' },
  reviewQuestion: { de: 'Wie war dein Erlebnis?', en: 'How was your experience?' },
  reviewPlaceholder: { de: 'Teile deine Erfahrung...', en: 'Share your experience...' },
  reviewSubmit: { de: 'Bewertung senden', en: 'Submit review' },
  reviewAlreadySubmitted: { de: 'Du hast diesen Termin bereits bewertet.', en: 'You already reviewed this appointment.' },
  reviewReply: { de: 'Antworten', en: 'Reply' },
  reviewResponse: { de: 'Deine Antwort', en: 'Your reply' },
  reviewResponseSend: { de: 'Antwort senden', en: 'Send reply' },
  reviewNoReviews: { de: 'Noch keine Bewertungen', en: 'No reviews yet' },
  reviewUnread: { de: 'Unbeantwortet', en: 'Unanswered' },
  reviewBased: { de: 'Basierend auf', en: 'Based on' },
  reviewEditResponse: { de: 'Bearbeiten', en: 'Edit' },

  chatTitle: { de: 'Nachrichten', en: 'Messages' },
  relativeJustNow: { de: 'Gerade eben', en: 'Just now' },
  relativeMinutesAgo: { de: 'vor {minutes} Min.', en: '{minutes} min ago' },
  relativeHoursAgo: { de: 'vor {hours} Std.', en: '{hours} hr ago' },
  relativeYesterday: { de: 'Gestern', en: 'Yesterday' },
  chatEmpty: { de: 'Noch keine Nachrichten', en: 'No messages yet' },
  chatEmptySub: { de: 'Starte ein Gespräch über deine Buchungen', en: 'Start a conversation about your bookings' },
  chatNoMessages: { de: 'Noch keine Nachrichten', en: 'No messages yet' },
  chatFirstMessage: { de: 'Sende die erste Nachricht', en: 'Send the first message' },
  chatPlaceholder: { de: 'Nachricht schreiben...', en: 'Write a message...' },
  chatOnline: { de: 'Online', en: 'Online' },
  chatOffline: { de: 'Offline', en: 'Offline' },
  chatTyping: { de: 'schreibt ...', en: 'typing ...' },
  chatSend: { de: 'Senden', en: 'Send' },

  notificationsTitle: { de: 'Benachrichtigungen', en: 'Notifications' },
  notificationsMarkAll: { de: 'Alle lesen', en: 'Mark all read' },
  notificationsEmpty: { de: 'Keine Benachrichtigungen', en: 'No notifications' },
  notificationsEmptySub: { de: 'Hier siehst du Updates zu deinen Buchungen', en: 'You will see updates about your bookings here' },
  notificationsToday: { de: 'Heute', en: 'Today' },
  notificationsYesterday: { de: 'Gestern', en: 'Yesterday' },
  notificationsAll: { de: 'Alle', en: 'All' },
  notificationsBookings: { de: 'Buchungen', en: 'Bookings' },
  notificationsMessages: { de: 'Nachrichten', en: 'Messages' },
  notificationsSystem: { de: 'System', en: 'System' },

  settingsTitle: { de: 'Einstellungen', en: 'Settings' },
  settingsAccount: { de: 'Account', en: 'Account' },
  settingsPersonalInfo: { de: 'Persönliche Informationen', en: 'Personal information' },
  settingsPassword: { de: 'Passwort ändern', en: 'Change password' },
  settingsNotifications: { de: 'Benachrichtigungen', en: 'Notifications' },
  settingsLegal: { de: 'Sicherheit & Rechtliches', en: 'Security & Legal' },
  settingsPrivacy: { de: 'Datenschutzerklärung', en: 'Privacy policy' },
  settingsTerms: { de: 'Nutzungsbedingungen', en: 'Terms of use' },
  settingsImprint: { de: 'Impressum', en: 'Imprint' },
  settingsLanguage: { de: 'Sprache', en: 'Language' },
  settingsLanguageDe: { de: 'Deutsch', en: 'Deutsch' },
  settingsLanguageEn: { de: 'English', en: 'English' },
  settingsLogout: { de: 'Abmelden', en: 'Sign out' },
  settingsDeleteAccount: { de: 'Account löschen', en: 'Delete account' },
  settingsDeleteTitle: { de: 'Möchtest du deinen Account wirklich löschen?', en: 'Do you really want to delete your account?' },
  settingsDeleteBody: {
    de: 'Alle deine Daten, Bewertungen und der Verlauf werden unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    en: 'All your data, reviews and history will be permanently deleted. This action cannot be undone.',
  },
  settingsDeleteEnterPassword: { de: 'Gib dein Passwort ein', en: 'Enter your password' },
  settingsDeletePasswordBody: { de: 'Bitte bestätige die Löschung mit deinem aktuellen Passwort.', en: 'Please confirm deletion with your current password.' },
  settingsDeleteFinal: { de: 'Endgültig löschen', en: 'Delete permanently' },
  settingsLogoutConfirm: { de: 'Wirklich abmelden?', en: 'Really sign out?' },
  settingsLogoutBody: { de: 'Möchtest du dich wirklich ausloggen?', en: 'Do you really want to sign out?' },
  settingsDiagnostics: { de: 'Diagnose', en: 'Diagnostics' },
  settingsDiagnosticsSendSentry: { de: 'Sentry-Test senden', en: 'Send Sentry test' },
  settingsDiagnosticsSent: { de: 'Test-Event wurde gesendet.', en: 'Test event sent.' },

  clientProfileTitle: { de: 'Profil', en: 'Profile' },
  clientProfileAddresses: { de: 'Meine Adressen', en: 'My addresses' },
  clientProfileSaved: { de: 'gespeichert', en: 'saved' },
  clientProfileReviews: { de: 'Meine Bewertungen', en: 'My reviews' },
  clientProfileHistory: { de: 'Buchungshistorie', en: 'Booking history' },
  clientProfileFavourites: { de: 'Meine Favoriten', en: 'My favourites' },
  clientProfileSwitchMode: { de: 'Mit anderem Anbieter-Konto anmelden', en: 'Sign in with a provider account' },
  clientProfileSwitchBody: {
    de: 'Du wirst abgemeldet und kannst dich danach mit einem separaten Anbieter-Konto anmelden.',
    en: 'You will be signed out and can then sign in with a separate provider account.',
  },
  emailVerified: { de: 'E-Mail verifiziert', en: 'Email verified' },
  phoneVerified: { de: 'Telefon verifiziert', en: 'Phone verified' },

  favouritesTitle: { de: 'Meine Favoriten', en: 'My favourites' },
  favouritesEmpty: { de: 'Noch keine Favoriten', en: 'No favourites yet' },
  favouritesEmptySub: { de: 'Entdecke Braider in deiner Nähe', en: 'Discover braiders near you' },
  favouritesDiscover: { de: 'Braider entdecken', en: 'Discover braiders' },
  favouritesRemoveTitle: { de: 'Aus Favoriten entfernen?', en: 'Remove from favourites?' },

  dashboardWelcome: { de: 'Willkommen zurück', en: 'Welcome back' },
  dashboardAvailable: { de: 'Verfügbar', en: 'Available' },
  dashboardUnavailable: { de: 'Nicht verfügbar', en: 'Unavailable' },
  dashboardAvailableSub: { de: 'Kunden können dich jetzt buchen', en: 'Customers can book you now' },
  dashboardUnavailableSub: { de: 'Du nimmst keine Buchungen an', en: 'You are not accepting bookings' },
  dashboardTodayAppts: { de: "Heute's Termine", en: "Today's appointments" },
  dashboardRating: { de: 'Bewertung', en: 'Rating' },
  dashboardThisWeek: { de: 'Diese Woche', en: 'This week' },
  dashboardNextAppt: { de: 'Nächster Termin', en: 'Next appointment' },
  dashboardTodaySchedule: { de: 'Heutiger Zeitplan', en: "Today's schedule" },
  dashboardOpenCalendar: { de: 'Kalender öffnen', en: 'Open calendar' },
  dashboardQuickAccess: { de: 'Schnellzugriff', en: 'Quick access' },
  dashboardNoAppts: { de: 'Keine weiteren Termine heute', en: 'No more appointments today' },
  dashboardStart: { de: 'Starten', en: 'Start' },
  dashboardEarnings: { de: 'Gewinnpotenzial heute', en: 'Potential earnings today' },

  bookingRequestTitle: { de: 'Buchungsanfrage', en: 'Booking request' },
  bookingRequestAlert: { de: '⚡ Schnell antworten!', en: '⚡ Respond quickly!' },
  bookingRequestAlertSub: { de: 'Kunden warten auf deine Bestätigung', en: 'Customers are waiting for your confirmation' },
  bookingRequestClient: { de: 'Kunde', en: 'Customer' },
  bookingRequestAccept: { de: 'Annehmen', en: 'Accept' },
  bookingRequestDecline: { de: 'Ablehnen', en: 'Decline' },
  bookingRequestDeclineTitle: { de: 'Buchung ablehnen', en: 'Decline booking' },
  bookingRequestDeclineBody: { de: 'Möchtest du diese Buchung wirklich ablehnen?', en: 'Do you really want to decline this booking?' },
  bookingRequestPrevious: { de: 'Bisherige Buchungen', en: 'Previous bookings' },
  bookingRequestLocation: { de: 'Ort', en: 'Location' },
  bookingRequestStudio: { de: 'In deinem Studio', en: 'In your studio' },
  bookingRequestConfirmed: { de: '✓ Du hast diesen Termin bestätigt', en: '✓ You confirmed this appointment' },
  bookingRequestDeclined: { de: '✗ Abgelehnt', en: '✗ Declined' },

  apptStart: { de: 'Termin starten', en: 'Start appointment' },
  apptComplete: { de: 'Termin abschließen', en: 'Complete appointment' },
  apptAccept: { de: 'Buchung annehmen', en: 'Accept booking' },
  apptDecline: { de: 'Ablehnen', en: 'Decline' },
  apptClientNote: { de: 'Notiz des Kunden', en: "Customer's note" },
  apptInfo: { de: 'Termininfo', en: 'Appointment info' },

  calendarTitle: { de: 'Terminkalender', en: 'Calendar' },
  calendarToday: { de: 'Heute', en: 'Today' },
  calendarNoAppts: { de: 'Keine Termine für diesen Tag', en: 'No appointments for this day' },
  calendarBlocked: { de: 'Blockiert', en: 'Blocked' },
  calendarAllDay: { de: 'Ganztägig', en: 'All day' },

  servicesTitle: { de: 'Services & Preise', en: 'Services & Prices' },
  servicesAdd: { de: 'Service hinzufügen', en: 'Add service' },
  servicesEdit: { de: 'Service bearbeiten', en: 'Edit service' },
  servicesInactive: { de: 'Inaktiv', en: 'Inactive' },
  servicesDeleteTitle: { de: 'Service löschen', en: 'Delete service' },
  servicesDeleteBody: { de: 'Möchtest du diesen Service wirklich unwiderruflich löschen?', en: 'Do you really want to permanently delete this service?' },
  servicesEmpty: { de: 'Noch keine Services hinzugefügt', en: 'No services added yet' },
  servicesPricePrefix: { de: 'Ab ', en: 'From ' },

  timeSuffix: { de: ' Uhr', en: '' },

  favouritesRemoveBody: { de: 'Möchtest du {name} wirklich aus deinen Favoriten entfernen?', en: 'Do you really want to remove {name} from your favourites?' },
  remove: { de: 'Entfernen', en: 'Remove' },
  selectedServicesGeneric: { de: 'Gewählte Services', en: 'Selected services' },
  bookedServices: { de: 'Gebuchte Services', en: 'Booked services' },
  approxDuration: { de: 'Ca. 2-3 Stunden', en: 'Approx. 2–3 hours' },
  cardGeneralTag: { de: 'Allgemein', en: 'General' },
  newLabel: { de: 'NEU', en: 'NEW' },
  responseTimeDefault: { de: '< 1 Stunde', en: '< 1 hour' },
  cancellationDefault: { de: '24 Stunden vor dem Termin', en: '24 hours before the appointment' },
  freeCancellationUntil: { de: 'Kostenlose Stornierung bis', en: 'Free cancellation until' },
  bookingWithinHour: { de: 'Innerhalb von 1 Stunde', en: 'Within 1 hour' },
  appointmentsEmptyCompleted: { de: 'Noch keine abgeschlossenen Termine', en: 'No completed appointments yet' },
  appointmentsEmptyCancelled: { de: 'Keine abgesagten Termine', en: 'No cancelled appointments' },
  appointmentsInfo: { de: 'Termininfo', en: 'Appointment info' },
  dashboardLoadError: { de: 'Fehler beim Laden der Daten.', en: 'Error loading data.' },
  blockTimeNoReason: { de: 'Kein Grund angegeben', en: 'No reason given' },
  servicesOtherCategory: { de: 'Sonstige', en: 'Other' },
  chatConnectionLost: { de: 'Verbindung unterbrochen. Versuche es erneut.', en: 'Connection lost. Trying again.' },

  addressesTitle: { de: 'Meine Adressen', en: 'My Addresses' },
  addressesEmpty: { de: 'Noch keine Adressen gespeichert', en: 'No addresses saved yet' },
  addressesEmptySub: { de: 'Füge eine Adresse hinzu für mobile Services', en: 'Add an address for mobile services' },
  addressesAdd: { de: 'Adresse hinzufügen', en: 'Add Address' },
  addressesEdit: { de: 'Adresse bearbeiten', en: 'Edit Address' },
  addressesDefault: { de: 'Standard', en: 'Default' },
  addressesSetDefault: { de: 'Als Standard setzen', en: 'Set as default' },
  addressesDeleteTitle: { de: 'Adresse löschen', en: 'Delete Address' },
  addressesDeleteBody: { de: 'Möchtest du diese Adresse wirklich löschen?', en: 'Do you really want to delete this address?' },
  addressesLabel: { de: 'Bezeichnung', en: 'Label' },
  addressesStreet: { de: 'Straße', en: 'Street' },
  addressesHouseNumber: { de: 'Hausnummer', en: 'House Number' },
  addressesPostalCode: { de: 'PLZ', en: 'Postal Code' },
  addressesCity: { de: 'Stadt', en: 'City' },
  addressesSave: { de: 'Speichern', en: 'Save' },
  addressesLabelPlaceholder: { de: 'Zuhause, Arbeit, Eltern...', en: 'Home, Work, Parents...' },
  addressesLoadError: { de: 'Adressen konnten nicht geladen werden. Bitte erneut versuchen.', en: 'Addresses could not be loaded. Please try again.' },
  addressesSetDefaultToggle: { de: 'Als Standardadresse festlegen', en: 'Set as default address' },
  addressesFillAllFields: { de: 'Bitte fülle alle Felder aus.', en: 'Please fill in all fields.' },
  addressesSaveError: { de: 'Die Adresse konnte nicht gespeichert werden.', en: 'The address could not be saved.' },

  personalInfoTitle: { de: 'Persönliche Informationen', en: 'Personal Information' },
  personalInfoFirstName: { de: 'Vorname', en: 'First Name' },
  personalInfoLastName: { de: 'Nachname', en: 'Last Name' },
  personalInfoEmail: { de: 'E-Mail', en: 'E-Mail' },
  personalInfoPhone: { de: 'Telefon', en: 'Phone' },
  personalInfoEmailNote: { de: 'E-Mail kann nicht geändert werden', en: 'Email cannot be changed' },
  personalInfoSave: { de: 'Änderungen speichern', en: 'Save Changes' },
  personalInfoAvatar: { de: 'Dein Profilbild', en: 'Your Profile Photo' },
  personalInfoNameRequired: { de: 'Vorname und Nachname dürfen nicht leer sein.', en: 'First name and last name cannot be empty.' },
  personalInfoPickImageError: { de: 'Fehler beim Auswählen des Bildes.', en: 'Error selecting the image.' },

  myReviewsTitle: { de: 'Meine Bewertungen', en: 'My Reviews' },
  myReviewsEmpty: { de: 'Noch keine Bewertungen', en: 'No reviews yet' },
  myReviewsEmptySub: {
    de: 'Deine Bewertungen nach abgeschlossenen Terminen erscheinen hier',
    en: 'Your reviews after completed appointments will appear here',
  },
  myReviewsViewAppts: { de: 'Termine ansehen', en: 'View Appointments' },
  myReviewsResponse: { de: 'Antwort des Anbieters:', en: 'Provider response:' },
  myReviewsUnknown: { de: 'Unbekannt', en: 'Unknown' },

  providerReviewsTitle: { de: 'Bewertungen', en: 'Reviews' },
  providerReviewsReply: { de: 'Antworten', en: 'Reply' },
  providerReviewsEdit: { de: 'Bearbeiten', en: 'Edit' },
  providerReviewsSubmit: { de: 'Antwort senden', en: 'Send Reply' },
  providerReviewsCancel: { de: 'Abbrechen', en: 'Cancel' },
  providerReviewsReplyTitle: { de: 'Auf Bewertung antworten', en: 'Reply to Review' },
  providerReviewsReplyPlaceholder: { de: 'Deine Antwort...', en: 'Your reply...' },
  providerReviewsEmpty: { de: 'Noch keine Bewertungen', en: 'No reviews yet' },
  providerReviewsEmptySub: { de: 'Deine ersten Kunden werden hier erscheinen', en: 'Your first customers will appear here' },
  providerReviewsFilter: { de: 'Unbeantwortet', en: 'Unanswered' },
  providerReviewsAll: { de: 'Alle', en: 'All' },
  providerReviewsBased: { de: 'basierend auf', en: 'based on' },
  providerReviewsCount: { de: 'Bewertungen', en: 'reviews' },
  providerReviewsOwnReply: { de: '✏️ Deine Antwort', en: '✏️ Your Reply' },

  availabilityTitle: { de: 'Verfügbarkeit', en: 'Availability' },
  availabilitySave: { de: 'Speichern', en: 'Save' },
  availabilitySaved: { de: 'Gespeichert ✓', en: 'Saved ✓' },
  availabilityClosed: { de: 'Nicht verfügbar', en: 'Not available' },
  availabilityFrom: { de: 'Von', en: 'From' },
  availabilityTo: { de: 'Bis', en: 'To' },
  availabilityBuffer: { de: 'Pufferzeit zwischen Terminen', en: 'Buffer time between appointments' },
  availabilityDaySun: { de: 'So', en: 'Sun' },
  availabilityDayMon: { de: 'Mo', en: 'Mon' },
  availabilityDayTue: { de: 'Di', en: 'Tue' },
  availabilityDayWed: { de: 'Mi', en: 'Wed' },
  availabilityDayThu: { de: 'Do', en: 'Thu' },
  availabilityDayFri: { de: 'Fr', en: 'Fri' },
  availabilityDaySat: { de: 'Sa', en: 'Sat' },

  providerEditTitle: { de: 'Profil bearbeiten', en: 'Edit Profile' },
  providerEditSave: { de: 'Änderungen speichern', en: 'Save Changes' },
  providerEditBio: { de: 'Über mich (Bio)', en: 'About Me (Bio)' },
  providerEditBioPlaceholder: { de: 'Erzähle deinen Kunden etwas über dich...', en: 'Tell your customers about yourself...' },
  providerEditRadius: { de: 'Service-Radius', en: 'Service Radius' },
  providerEditLanguages: { de: 'Sprachen', en: 'Languages' },
  providerEditCancellation: { de: 'Stornierungsrichtlinie', en: 'Cancellation Policy' },
  providerEditCancel24: { de: '24 Stunden', en: '24 Hours' },
  providerEditCancel48: { de: '48 Stunden', en: '48 Hours' },
  providerEditCancel72: { de: '72 Stunden', en: '72 Hours' },
  providerEditCancel24Desc: { de: 'Kostenlose Stornierung bis 24h vorher', en: 'Free cancellation up to 24h before' },
  providerEditCancel48Desc: { de: 'Kostenlose Stornierung bis 48h vorher', en: 'Free cancellation up to 48h before' },
  providerEditCancel72Desc: { de: 'Kostenlose Stornierung bis 72h vorher', en: 'Free cancellation up to 72h before' },
  providerEditStreet: { de: 'Straße', en: 'Street' },
  providerEditHouseNumber: { de: 'Nr.', en: 'No.' },
  providerEditPostalCode: { de: 'PLZ', en: 'Postal Code' },
  providerEditCity: { de: 'Stadt', en: 'City' },
  providerEditName: { de: 'Business-Name / Dein Name', en: 'Business Name / Your Name' },
  providerEditPickImageError: { de: 'Fehler beim Auswählen des Bildes.', en: 'Error selecting the image.' },
  providerEditDisplayNamePlaceholder: { de: 'Dein Anzeigename', en: 'Your display name' },

  blockTimeTitle: { de: 'Zeit blockieren', en: 'Block Time' },
  blockTimeReason: { de: 'Grund', en: 'Reason' },
  blockTimePeriod: { de: 'Zeitraum', en: 'Period' },
  blockTimeStartDate: { de: 'Startdatum', en: 'Start Date' },
  blockTimeEndDate: { de: 'Enddatum', en: 'End Date' },
  blockTimeAllDay: { de: 'Ganztägig', en: 'All Day' },
  blockTimeTime: { de: 'Uhrzeit', en: 'Time' },
  blockTimeFrom: { de: 'Von', en: 'From' },
  blockTimeTo: { de: 'Bis', en: 'To' },
  blockTimeRepeat: { de: 'Wiederholen', en: 'Repeat' },
  blockTimeRepeatSub: { de: 'Zeit regelmäßig blockieren', en: 'Block time regularly' },
  blockTimeSubmit: { de: 'Zeit blockieren', en: 'Block Time' },
  blockTimeReasonVacation: { de: 'Urlaub', en: 'Vacation' },
  blockTimeReasonSick: { de: 'Krank', en: 'Sick' },
  blockTimeReasonAppointment: { de: 'Persönlicher Termin', en: 'Personal Appointment' },
  blockTimeReasonBreak: { de: 'Pause', en: 'Break' },
  blockTimeReasonOther: { de: 'Sonstiges', en: 'Other' },

  notificationsReadAll: { de: 'Alle lesen', en: 'Mark all read' },
  notificationsAgoMins: { de: 'vor {minutes} Min.', en: '{minutes} min ago' },
  notificationsAgoHours: { de: 'vor {hours} Std.', en: '{hours} hr ago' },
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS;
export type Lang = 'de' | 'en';

// ─── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'de',
  setLang: async () => {},
  t: (key) => (TRANSLATIONS as Record<string, { de: string; en: string }>)[key]?.de ?? key,
});

// ─── Provider ─────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('de');

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const saved = await tokenStorage.getLanguage();
        if (!cancelled) setLangState(saved);
      } catch (error) {
        Sentry.captureException(error);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  const setLang = useCallback(async (newLang: Lang) => {
    setLangState(newLang);
    await tokenStorage.setLanguage(newLang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      const entry = (TRANSLATIONS as Record<string, { de: string; en: string }>)[key];
      return entry?.[lang] ?? entry?.de ?? key;
    },
    [lang],
  );

  return React.createElement(LanguageContext.Provider, { value: { lang, setLang, t } }, children);
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
export function useLanguage() {
  return useContext(LanguageContext);
}
